### ISSUE TITLE
Problems Deploying

### ISSUE THREAD

**Issue by keevan163** [Toddez/graphing-calculator#1]
I was trying to deploy to repl.it

I can't - the packages are non-existent.

**Comment by Toddez** [comment]
I'm not familiar with repl.it, if it's a problem with installing the packages then I could not reproduce the problem by cloning and running ``yarn install``.

However running ``npm install`` may not work as there's no ``package-lock.json``. If you attempted to use npm, then either switch to yarn or generate your own lock file from the ``yarn.lock``.
